FROM node:22.11.0 as build
WORKDIR /app
COPY . .
RUN rm -rf node_modules package-lock.json
RUN npm i --force --foreground-scripts
RUN npm run build lmsn -- --prod --output-path=/dist --skip-nx-cache --base-href="/lmsn/"
################
# Run in NGINX #
################
FROM nginx:alpine
COPY --from=build /dist /var/www/frontend-lms
RUN apk update && apk add bash nano iputils
COPY frontend.version frontend.version
COPY front-dev.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
